CREATE TABLE "GCG_4442_METAL_PROG"(
 "JOB" VARCHAR(6),
 "SUFFIX" VARCHAR(3),
 "PART" VARCHAR(20),
 "DESCRIPTION" VARCHAR(30),
 "QTY_ORDER" DOUBLE,
 "QTY_COMPLETED" DOUBLE,
 "GRID" VARCHAR(3),
 "PRIORITY" INTEGER,
 "ORDER_NO" VARCHAR(7));
