CREATE TABLE "GCG_4442_WPROG_HIST"(
 "HIST_NO" IDENTITY,
 "GRID" VARCHAR(3),
 "JOB" VARCHAR(6),
 "SUFFIX" VARCHAR(3),
 "PART" VARCHAR(20),
 "QTY" DOUBLE,
 "CHECK_IN" VARCHAR(30),
 "CHECK_OUT" VARCHAR(30));
